leancloud/js-realtime-sdk

src/AV.realtime.js

Fix a typo in `Conversation.update` which will block conversation attribute update.

fix(Conversation): Fix typo in Conversation.update

---

src/AV.realtime.js

ie9问题参考如下：
https://social.msdn.microsoft.com/Forums/ie/en-US/30ef3add-767c-4436-b8a9-f1ca19b4812e/ie9-rtm-xdomainrequest-issued-requests-may-abort-if-all-event-handlers-not-specified?forum=iewebdevelopment
304问题是查了很久才发现的。

对ie9中XDomainRequest执行不稳定，及ie9下第一个请求304时,xdr一直onerror

---

src/AV.realtime.js

[bugfix] 重复绑定底层事件，事件中心增加 one，realtime 暴露 clientId。

---

src/realtime.js

Option `ssl` only decided whether to use websocket over SSL. Router protocol is no longer configable.

[feat] make secure option decided ws/wss only

---

src/realtime.js
src/utils.js
src/websocket-plus.js
test/realtime.js
test/websocket-plus.js

目前的 SDK 只暴露了 `disconnect` 与 `reconnect` 两个事件，无法满足更加精细的断线重连提示。举个例子，bearychat 断线后会显示：
>7 秒后重新连接 ··· 立即重连
>正在重新连接 ···
这个 RP 为 WebSocketPlus 增加了 `reconnecting` 状态与 `schedule` 事件，为 Realtime 增加了 `retry` 方法，调用该方法会立即重连并重置尝试计数器。
更新后的 WebSocketPlus 状态转移描述如下：
在一个典型的断线重连流程中，Realtime 实例会依次派发以下事件：
```
disconnect
schedule (attempt=0, delay=1000)
retry (attempt=0)
schedule (attempt=1, delay=2000)
retry (attempt=1)
schedule (attempt=2, delay=4000)
[call realtime.retry()]
retry (attempt=0)
schedule (attempt=1, delay=2000)
retry (attempt=1)
reconnect
```
cc @leancloud/ios-group @leancloud/android-group

feat(Realtime): Add event retry and schedule

---

.travis.yml
src/realtime.js

Currently there is no persistent storage implemented, hence the push routers are mem-cached only.

feat(Realtime): support app router

---

Gruntfile.js
package.json
typed-messages/src/file-message.js
typed-messages/src/realtime.js
typed-messages/src/storage.js

使用了 rollup 内置的外部依赖加载方式代替自己写的加载器从而添加了 AMD loaders 的支持。
兼容 SDK 1.0.0-rc.9 的 AV.File 数据结构。

fix(TypedMessages): add support to AMD loaders

---

.jsdocrc.json
Gruntfile.js
README.md
src/websocket-plus.js
test/websocket-plus.js

Previously, if the connection is not connected, calling APIs invoking WebSocketPlus#send will throw `null is not an object(evaluating 'this._ws.send')`, which is not helping.
This commit decorate WebSocketPlus#send with connection state checking which throws meaningful error and warning.
cc @han4wluc

fix(WebSocketPlus): check connection state when calling #send

---

src/browser/ws.js

Previously, globel.WebSocket was assigned accidentally(https://github.com/leancloud/js-realtime-sdk/blob/v3.0.0/dist/realtime.browser.js#L4243), which caused crashes in React Native as global.WebSocket is readonly.
fix #281.

fix: stop assigning global WebSocket

---

src/im-client.js
test/conversation-query.js

when quering conversations with lastMessage flag, the lastMessage get the correct from/id/timestamp now.
https://leanticket.cn/t/leancloud/2105

feat(ConversationQuery): support more lastMessage metaData

---

src/conversation.js
src/realtime.js
test/conversation.js

including: attributes setter and getter, setAttribute, setAttributes, setName
详细说明：https://url.leanapp.cn/DeprecateAttributes
also: add Realtime.defineConversationProperty to make it easy to define custom properties for Conversation
不想因此 export Conversation，所以这个 API 是 Realtime 的静态方法，不知道有没有更好的设计。

feat(Conversation): make get, set public and deprecate attributes setter APIs

---

src/conversation.js
src/im-client.js
src/index.js
src/messages/message.js
src/realtime.js
test/conversation-query.js
test/conversation.js
test/messages.js

Add status property to Message and export MessageStatus: `NONE`, `SENDING`, `SENT`, `DELIVERED`, `FAILED`.
If set to `needReceipt`, a message will turn to `DELIVERED` status once it's delivered.
Also a `receipt` event will be emitted on the conversation the message was send to.

feat(Message): implement message receipt

---

src/websocket-plus.js

In Safari, when air mode is on, the connecting failure can only be caught in onclose event.
Fix issue that the first reconnect attempt will be penging forever.

fix(WebSocketPlus): also catch error on close event

---

demo/simple-chatroom/test.js
src/realtime.js
src/websocket-plus.js
test/realtime.js
test/websocket-plus.js

目前，SDK 连接层有下面几个状态：
有两个问题：
- 网络断开时，由于 WebSocket 实现内置有重连机制，SDK 不会立即感知到断开，而此时消息发送均会失败，这个过程有时会长达 3 分钟直到心跳检测失败。
- 在明确感知到网络断开的情况下，SDK 是不应该尝试重连的。
同样的问题在 React Native 或小程序应用前后台切换时也存在。参见 #421 https://forum.leancloud.cn/t/websocket/12774
为了解决这个问题，这个 PR 为 SDK 增加了一个 `offline` 状态（原来的 `offline` 状态改名为 `disconnected`）：
在浏览器上，SDK 通过监听 window 的 `offline`/`online` 事件，当网络断开时 pause SDK，网络恢复时 resume SDK 然后开始重连。用户可以通过 Realtime 或 IMClient 派发的 `offline`/`online` 事件在用户界面上作出相应的提示。改动后，一次断网恢复的过程中 SDK 会依次派发以下事件：
```
[offline] 离线（网络连接已断开）
[disconnect] 服务器连接已断开
[online] 已恢复在线
[schedule] 1s 后进行第 1 次重连
[retry] 正在进行第 1 次重连
[reconnect] 重连成功
```
对于 React Naitve 的网络变化、RN 与小程序的前后台切换以及其他的场景，Realtime 增加 `pause` 与 `resume` 方法供开发者手动控制 SDK 的离线状态。
close #421

feat(WebSocketPlus): add new offline state

---

changelog.md
proto/message-compiled.js
proto/message.proto
realtime.d.ts
src/conversation.js
src/im-client.js
src/messages/message.js
src/realtime.js
src/utils/cache.js
src/utils/index.js
test/conversation.js
test/im-client.js
test/messages.js
test/utils.js

add Conversation#read
deprecate Conversation#markAsRead
deprecate IMClient.markAllAsRead
add Conversation#fetchReceiptTimestamps
add Conversation#event:lastdeliveredatupdate
add Conversation#event:lastreadatupdate
deprecate Conversation#event:receipt
implement https://github.com/leancloud/avoscloud-push/issues/675#issuecomment-282961128
还修正了 sendOption.reciept 参数的拼写错误，简直尴尬。

feat(Conversation): support read timestamp

---

src/websocket-plus.js
test/websocket-plus.js

之前如果网络断开再恢复，派发的事件的顺序是 ['offline', 'disconnect', 'online', 'schedule']
用户如果分别对 'disconnect', 'offline' 进行 UI 上的更新的话，最终看到的会是 disconnect 的提示。
调整成 ['disconnect', 'offline', 'online', 'schedule'] 会让 UI 的工作更简单。

fix(WebScoketPlus): emit disconnect event before offline

---

src/conversation.js
src/im-client.js
test/conversation.js

让 `unreadmessagescountupdate` 事件更加贴合其意思，主要做了两件事：
1. 过滤掉了 Conversation 的 unreadMessagesCount 没有变化的情况
2. 当收到在线消息时，也派发 `unreadmessagescountupdate` 事件

refactor(unread): filter unread events which not accutally changed

---

src/im-client.js

如果收到当前 client 其他设备发送的 message，需要跳过：
- 未读消息数累加
- 发送 ack
其他行为，包括派发 message 事件，保持不变。

fix: skip handling synced outgoing messages

---

src/conversation.js

fix an issue that the last message will not be marked as read caused by inaccurate lm.
cc @ylgrgyq

fix(Read): only update Conversation#lastMessageAt with a later timestamp

---

src/plugin-im.js

为了实现 createIMClient 的单例模式，设置了一个 map 来存正在 open 或已经 open 的 clients。但是在 open 失败的时候没有正确的删除对应恩 client 导致后续的 create 都会得到这个失败的结果。
https://leanticket.cn/tickets/13357

fix(IMClient): delete client when failed opening

---

src/plugin-im.js

_dispatchCommand returns undefined sometimes. This issue is already fixed in v4 as _dispatchCommand is async. This commit is a quick fix for v3.

fix(IM): ensure IMClient#_dispatchCommand returns Promise

---

demo/simple-chatroom/index.html
demo/simple-chatroom/test.js
plugins/live-query/test/index.js
src/im-client.js
src/plugin-im.js
src/realtime.js
src/signature-factory-runner.js
test/conversation-query.js
test/conversation.js
test/im-client.js
test/messages.js
test/plugin.js
test/realtime.js

用户能感知到的变动：
- 初始化 Realtime 必须提供 appKey
- Realtime#createIMClient 接收 AV.User 为第一个参数
- 更新到了 AppRouter 2，域名变了
内部变动：
- 增加了 realtime#_request
- 因为验证签名的开关会影响现有的 case，这个功能不太好测试，因此新建了一个应用更新了 demo/simple-chatroom。

feat(IMClient): support createIMClient with an AV.User

---

src/plugin-im.js
test/realtime.js

sometimes unread/direct commands will be dispatched before client initialized.

fix(IM): block commands until IMClient initialized

---

realtime.d.ts
src/conversation.js
src/im-client.js
src/plugin-im.js
test/conversation.js

deprecate beforeTime, beforeMessageId, afterTime and afterMessageId options.
close #569.

feat(Conversation): add messages query direction support

---

.travis.yml
babel.config.js
package-lock.json
package.json
rollup/shared-configs.js
test/configs.js

- 移除已废弃的依赖: `@babel/runtime-corejs2` > `corejs@2`(deprecated)
- 更新 serverURL (之前的证书过期了)

build: remove @babel/runtime-corejs2

---

realtime.d.ts

相关工单: https://www.leanticket.cn/tickets/36979
之前的定义约束不够，缺少 Message.parse 、Message.validate 和 TypedMessage.TYPE 。
看了下 helpers.js 里这两个函数的用法，只要求 target 是 TypedMessage Class 即可（文档里也是这么说的），就把泛型参数去掉了。

fix: type definition of messageType & messageField

---

realtime.d.ts
src/conversations/persistent-conversation.js
test/conversation.js

- add/remove action is renamed to invite/kick  to align with the document (This is breaking for users of conversation signature).
- swap the clientId and the convId param for blacklistSignatureFactory (This is breaking for users of blacklist signature).
- fix the conversationSignature order in ts definition.
close https://www.leanticket.cn/tickets/37033

fix(signature): unify action name and param order

---

src/im-client.js

See: leancloud/rfcs#1089
JS 的实现方式：
JS SDK 中没有「默认 peerId」这个概念，创建 IMClient 时设置了 clientId 就用它当 peerId ，未设置 clientId 时使用后端返回的 peerId 。
若 Connection 中仅有一个 IMClient ，发送命令时省略 peerId（之前发送 ACK 时还是会带上，这次也去掉了），若有多个 IMClient 则不省略 peerId 。
收到的命令如果携带 peerId 就将其派发给对应的 IMClient ，否则派发给第一个创建的 IMClient 。

feat(im-client): support omit peer id

---

realtime.d.ts

感觉这里定义错了，`IMClient#getConversation` 返回 `IMClient#getQuery` 的查询结果，所以应该也是 `PresistentConversation`

fix: type definition of IMClient#getConversation

---

src/plugin-im.js
src/realtime.js

Realtime 和 IM Plugin 都记录了创建资源的 Promise ，这两个地方都需要在失败的时候清理一下。

fix: remove rejected promise

---

plugins/typed-messages/src/index.js
rollup/rollup.config.plugins.js

在浏览器中，富媒体消息插件默认导出的初始化函数会覆盖由存储 SDK（或 IM SDK）设置的 AV 命名空间。
最初没想到这一点，这个改法算是抢救一下吧。但确实挺好用的。

feat(plugin/typed-messages): auto init in browser

---

plugins/typed-messages/test/index.js
test/configs.js

之前测试应用的域名证书过期了，就换成共享域名继续使用了。但设置错了，应该用 appId 的前 8 位结果设置成 appKey 的前 8 位了。神奇的是测试用例都能跑过。
富媒体消息的测试用的是 3.x 的存储 SDK，会自动根据 appId 使用共享域名，但自动拼接的 https://xxxxxxxx.api.lncld.net 的域名现在也不能用了。也手动设置一下 serverURLs 罢。

fix: test app server
