leancloud/js-realtime-sdk

bower.json
changelog.md
src/AV.realtime.js

[feature] 2.0.2 发布相关。

---

src/AV.realtime.js

[feature] 开放 secure 选项，可以将 wss -> ws 。

---

demo/demo2/test.js

@sunng87 仍然总是有用户只是试了下 demo，就说不兼容的问题，demo 中关闭安全链接。

[feature] Demo2 中关闭 secure。

---

demo/demo1/test.js
src/AV.realtime.js

[bugfix] Room 初始化属性存储结构修改。

---

src/AV.realtime.js

[bugfix] 防止同一个 realtime 实例可能产生两个 websocket 实例。

---

src/AV.realtime.js

diff 不是很清晰，其实就是将 engine 方法提到外面，然后 engine 方法都增加第一个参数为 cache。

[bugfix] 修复同一 runtime 多实例的 bug。

---

src/AV.realtime.js

[chore] 移除 appId，暂态消息不回复 ack 

---

.gitignore
Gruntfile.js
bower.json
changelog.md
package.json
src/realtime.js
test/browser/index.html
test/browser/runner.js
test/runner.js
test/specs.js

ws 配置了 bowser 字段，直接用打包时会自动替换为浏览器内置实现。现内置作为 SDK 的依赖，则无需要求用户在 node 中使用时事先进行配置。

[feat] Use ws as the default WebSocket implement in node.

---

src/realtime.js
test/specs.js

[feat] Unique conversation support.

---

src/realtime.js
test/specs.js

[feat] Support conv query flags.

---

src/conversation.js
src/im-client.js
test/im-client.js

feat(IMClient): add IMClient#markAllAsRead()

---

typed-messages/src/file-message.js
typed-messages/test/file-message-and-subclasses.js

fix(FileMessage): loose the parser to be compatible with non-standard messages

---

Gruntfile.js
package.json
src/realtime.js

Modify rollup config to transform axios as well since it uses Promise.
Hopefully fix #214

fix(Realtime): replace superagent with axios to prevent false CORS errors

---

src/conversation-query.js
src/im-client.js
test/conversation-query.js
test/conversation.js
test/im-client.js
test/realtime.js
test/signature-factory-runner.js
test/test-utils.js
test/utils.js
test/websocket-plus.js

see commit messages for more details.

Override conversation properties properly

---

src/im-client.js

fix(Realtime): handle message dispatch promise rejection

---

src/conversation.js
test/conversation.js

fix(MessageIterator): copy the result array before resolving it

---

Gruntfile.js
README.md
src/messages/helpers.js
src/messages/text-message.js
src/messages/typed-message.js
src/realtime.js
src/utils.js
test/messages.js
test/realtime.js

顺带 fix IE 11 中 使用 TypedMessages 报 `Object.assign` 不存在的错误。

feat: IE10 compatible

---

src/conversation-query.js
test/conversation-query.js

fix ascending, addAscending, descending, addDescending not working issue. https://forum.leancloud.cn/t/javascript-sdk-conversationquery/9935

fix(ConversationQuery): add sort field to the query string

---

package.json
src/conversation.js
src/realtime.js
test/im-client.js
test/realtime.js

fix resolve error in React Native.
fix #317

fix resolve error in React Native.

---

src/errors.js
src/im-client.js
src/realtime.js
src/utils/cache.js
src/utils/expirable.js
src/utils/index.js
test/im-client.js

implement https://github.com/leancloud/avoscloud-push/issues/471
API changes:
- Add events to IMClient: `disconnect`, `reconnect`, `reconnecterror`, `retry`, `schedule`

Feat sessiontoken

---

.babelrc
Gruntfile.js
package.json

close #333 close #334 close #335 close #336 close #337

chore(package): remove babel-preset-es2015-rollup

---

.babelrc
package.json
src/conversation.js
src/im-client.js
src/utils/index.js
test/conversation.js
test/utils.js

fix(Conversation): add new private _set method and reimplement setAttribute[s]

---

package.json
src/realtime.js

group events in docs

---

src/im-client.js
src/realtime.js

fix(IMClient): use an internal ee to prevent internal events removed by user

---

src/im-client.js
test/conversation.js

Also update conversation.lastMessageAt with payload.lastMessageTimestamp as the original conv.lm is not accurate.

fix(unread): correct invalid unreadmessage event payload.lastMessageTimestamp

---

src/im-client.js

https://github.com/leancloud/docs/issues/1473

docs(Events): use plural form with members related events

---

proto/message-compiled.js
proto/message.proto
src/conversation.js
src/im-client.js
src/index.js
test/conversation.js

add Conversation#updateOnlineStatusPolicy method
add Conversation#membersstatuschange event

feat(Conversation): implement onlineStatus

---

src/conversation.js
src/im-client.js
src/index.js
test/conversation.js

This reverts commit 61297d4429f0bf4b6b266d1d162c5f18e73a57d7
see: https://github.com/leancloud/paas/issues/862
message.proto is not reverted.

revert: feat(Conversation): implement onlineStatus (#363)

---

src/conversation.js
src/error.js
src/index.js
src/messages/av-message.js
src/messages/message.js
test/messages.js

see commit messages for details.

feat: sendOptions

---

src/conversation.js
src/messages/message.js

also deprecate `Message#setTransient()`

fix(Conversation): add missing sendOptions.transient

---

package.json
src/realtime.js

and upgrade polyfill
request for push router with feature=wechat will return a fixed set of endpoints.

feat(Weapp): use feature param of push router for fixed domain list

---

Gruntfile.js
package.json

https://github.com/visionmedia/debug/issues/363
https://github.com/leancloud/weapp-polyfill/commit/4c13db3c1f4b71fe92409794815474de22a4a6e8
以及发布 uglify 之后的 realtime.weapp.min.js

fix: upgrade debug and weapp-polyfill to deal with nullable navigator and userAgent

---

src/conversation.js

https://forum.leancloud.cn/t/topic/12961 😅
暂态消息不太好测啊。

fix(Conversation): fix sendOptions.transient not working

---

src/im-client.js

https://forum.leancloud.cn/t/javascript/14341

fix: ignore deleted conversations when dealing with unread and direct commands

---

realtime.d.ts
src/websocket-plus.js

https://github.com/leancloud/paas/issues/938

Change ping interval to 180s

---

proto/message-compiled.js
proto/message.proto
realtime.d.ts
src/conversation.js
src/im-client.js
src/messages/message.js
test/conversation.js
test/messages.js

https://github.com/leancloud/paas/issues/953

feat: mention

---

package.json
realtime.d.ts
src/conversation.js
src/im-client.js
src/messages/binary-message.js
src/messages/message.js
src/plugin-im.js
test/messages.js

https://github.com/leancloud/paas/issues/951

feat: BinaryMessage

---

src/im-client.js

之前在收到 session close command 的时候，没有正确的断掉 session。

fix(IM): dispatch an internal close event on CLOSE command

---

proto/message-compiled.js
proto/message.proto
realtime.d.ts
src/conversation-query.js
src/conversations/chat-room.js
src/conversations/conversation-base.js
src/conversations/conversation.js
src/conversations/index.js
src/conversations/persistent-conversation.js
src/conversations/service-conversation.js
src/conversations/temporary-conversation.js
src/error.js
src/eventemitter.js
src/im-client.js
src/messages/message.js
src/messages/typed-message.js
src/plugin-im.js
test/conversation.js
test/im-client.js
test/messages.js
test/websocket-plus.js

feat: ChatRoom, ServiceConversation and TemporaryConversation

---

package.json
src/realtime.js

- stop using base64 encoded frames in weapp
- offline/online detection in weapp

feat: upgrade weapp-polyfill

---

src/im-client.js
test/im-client.js

related issue: leancloud/paas#1024

feat(conversation): unique is true by default

---

realtime.d.ts

thanks to @wpcfan for report
close #616

fix(ts): queryMessages para typing

---

realtime.d.ts
src/conversation-query.js
src/im.js
test/conversation-query.js

feat(query): add "and", "or" function to ConversationQuery

---

src/connection.js
src/utils/index.js
test/realtime.js
test/utils.js

https://github.com/leancloud/rfcs/issues/1056

perf: throttle duplicated pending commands

---

README.md
demo/simple-chatroom/index.html

fix: update outdated link

---

src/conversations/persistent-conversation.js

Close #651
已有的测试能跑通，不为这个用法单独写测试了。不过我还是不确定是否应该实现这种用法，[点号使用指南](https://leancloud.cn/docs/dot-notation.html) 中的用例都是查询或修改保存在云端的 Object 。

feat: get attributes with dot syntax

---

changelog.md
package-lock.json
package.json

@leeyeh 补充下 da9673938b1a42fd22854baa0ddeb3d5ed1c0e36 和 01eb760299637dc6204e4309b0071cb23ae21968 的 changelog

chore(release): v5.0.0-rc.4

---

src/conversations/conversation-base.js

leancloud/rfcs#1093
https://github.com/leancloud/js-realtime-sdk/blob/55003ecbd619fdb53381bcee3a3e3409ccde57fe/src/im-client.js#L759-L761
https://github.com/leancloud/js-realtime-sdk/blob/55003ecbd619fdb53381bcee3a3e3409ccde57fe/src/conversations/conversation-base.js#L692-L693

feat: disable max_read command in transient/system conversation

---

realtime.d.ts
src/realtime.js

BREAKING CHANGE: use unread notification instead

feat: remove support for pushOfflineMessages mode

---

src/im-client.js

context: https://xindong.slack.com/archives/C01S87YPYR0/p1620452078048000

fix(temp-conv): remove the default falsy unique option

---

src/conversations/conversation-base.js

用户反馈撤回消息出错: https://www.leanticket.cn/tickets/37495
修改消息也有同样的问题。

fix(conversation): get id of undefined lastMessage

---

demo/webrtc/index.js

修复 WebRTC demo 不能加载的问题，需要设置 server url 才能加载。

fix(demo): set server url

---

demo/simple-chatroom/index.html

see also https://github.com/leancloud/js-realtime-sdk/pull/675#discussion_r668673482

fix: version typo

---

src/realtime.js

fix: typo aleady -> already

---

package-lock.json
package.json

Reverts leancloud/js-realtime-sdk#688

Revert "chore(deps): bump protobufjs from 5.0.3 to 6.11.3"
